apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: minimal-curl
            image: minimal-curl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; curl my-service.default.svc.cluster.local/hello
          restartPolicy: OnFailure
